# There is a explanation of the necessary of this file in the README.md file.

# 
locals {                                                    # Create a const variables for not repeating the same string in multiple places.`
  alb_controller_namespace = "kube-system"                  # The namespace where the ALB controller service account will be created. It should be the same as the namespace where the ALB controller will be deployed.
  alb_controller_sa_name   = "aws-load-balancer-controller" # The name of the service account that will be created for the ALB controller.
  eks_oidc_issuer          = replace(data.aws_eks_cluster.this.identity[0].oidc[0].issuer, "https://", "")
}

# Here we create a set of rules that define who can assume the IAM Role that we will create for the ALB controller.
data "aws_iam_policy_document" "alb_controller_assume_role" {
  statement { # Here we make a statement that allows to assume role from web identity that is not the aws, it's the OIDC provider (the EKS cluster).  
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {                                                                                                           # Here we define the recipient of this assume role, in this case, it's the OIDC provider of the EKS cluster.
      type        = "Federated"                                                                                            # This means that the principal is an external identity provider.
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:oidc-provider/${local.eks_oidc_issuer}"] # The ARN of the OIDC provider of the EKS cluster.
    }

    condition {                 # Here we define whom is the recipient of the token that will be generated by the OIDC provider, in this case, is the sts service of AWS. 
      test     = "StringEquals" # the condition below must match word-for-word, and regex is not allowed.
      variable = "${local.eks_oidc_issuer}:aud"
      values   = ["sts.amazonaws.com"]
    }

    condition { # Here we define the subject of the token (who can use this token), in this case, it's the ServiceAccount that we we created for the ALB controller, and we  
      test     = "StringEquals"
      variable = "${local.eks_oidc_issuer}:sub"
      values   = ["system:serviceaccount:${local.alb_controller_namespace}:${local.alb_controller_sa_name}"]
    }
  }
}

resource "aws_iam_role" "alb_controller" { # Here we create the IAM Role for the ALB controller, and we attach the assume role policy that we created above.
  name               = "calculator-dev-alb-controller-irsa"
  assume_role_policy = data.aws_iam_policy_document.alb_controller_assume_role.json
}

# Full explanation of this block you will find in the README file.
# Here we allow the ALB controller to create the ELB "ServiceLinkedRole". This service linked role is necessary for the ALB controller to work, and it will be created automatically by the ALB controller when it needs it. The porpuse of this "ServiceLinkedRole" (in IAM category) is to allow the ALB controller to call the ELB API when he needs to create or manage an ALB.
data "aws_iam_policy_document" "alb_controller_permissions" {
  statement {
    sid       = "AllowELBServiceLinkedRole" # Semantically unique identifier for the statement, it's not necessary but it's a good practice to have it for better readability.
    effect    = "Allow"
    actions   = ["iam:CreateServiceLinkedRole"] # Here we allow to create service linked role.
    resources = ["*"]                           # Here we allow to create service linked role for any resource, and we will use a condition to restrict this permission to only the ELB service linked role.

    condition {
      test     = "StringEquals"
      variable = "iam:AWSServiceName"
      values   = ["elasticloadbalancing.amazonaws.com"] # Here we restrict the permission to create service linked role only for the ELB (ALB here) .
    }
  }

  statement {
    sid    = "AllowAlbControllerCorePermissions" # Semantically unique identifier for the statement, it's not necessary but it's a good practice to have it for better readability.
    effect = "Allow"
    actions = [ # List of actions that the ALB controller allow to perform on the call to AWS API, this list is based on the official documentation of the ALB controller, and it's necessary for the ALB controller to work properly. 
      "acm:DescribeCertificate",
      "acm:ListCertificates",
      "cognito-idp:DescribeUserPoolClient",
      "ec2:AuthorizeSecurityGroupIngress",
      "ec2:CreateSecurityGroup",
      "ec2:CreateTags",
      "ec2:DeleteSecurityGroup",
      "ec2:DeleteTags",
      "ec2:Describe*",
      "ec2:GetCoipPoolUsage",
      "ec2:ModifyInstanceAttribute",
      "ec2:ModifyNetworkInterfaceAttribute",
      "ec2:RevokeSecurityGroupIngress",
      "elasticloadbalancing:*",
      "iam:GetServerCertificate",
      "iam:ListServerCertificates",
      "shield:CreateProtection",
      "shield:DeleteProtection",
      "shield:DescribeProtection",
      "shield:GetSubscriptionState",
      "tag:GetResources",
      "waf-regional:AssociateWebACL",
      "waf-regional:DisassociateWebACL",
      "waf-regional:GetWebACL",
      "waf-regional:GetWebACLForResource",
      "wafv2:AssociateWebACL",
      "wafv2:DisassociateWebACL",
      "wafv2:GetWebACL",
      "wafv2:GetWebACLForResource"
    ]
    resources = ["*"] # Here we allow to ALB controller to perform the above actions on any resource in the account, and we using conditions to restrict this permission to only the ALB controller with his ServiceAccount in the kube-system namespace, but we can't restrict to specific resources (ALB) because the ALB doesn't exist yet. 
  }
}

resource "aws_iam_policy" "alb_controller" { # Here we create the IAM Policy for the ALB controller, and we attach the permissions policy that we created above.
  name   = "calculator-dev-alb-controller-policy"
  policy = data.aws_iam_policy_document.alb_controller_permissions.json
}

resource "aws_iam_role_policy_attachment" "alb_controller" { # Here we attach the IAM policy to the ALB controller IAM Role.
  role       = aws_iam_role.alb_controller.name              # Here we specify the name of the IAM Role that we created above.
  policy_arn = aws_iam_policy.alb_controller.arn
}

resource "kubernetes_service_account_v1" "alb_controller" { # Here we create the Kubernetes Service Account for the ALB controller, 
  metadata {                                                # Here we specify for AWS that this Service Account is the one that will be used by the ALB controller
    name      = local.alb_controller_sa_name                # The name of the Service Account.
    namespace = local.alb_controller_namespace              # The namespace where the Service Account will be created.
    annotations = {                                         # Here we are linking the Service Account with the IAM Role that we created above. 
      "eks.amazonaws.com/role-arn" = aws_iam_role.alb_controller.arn
    }
  }
}
